
def _seed():
    existing = query("SELECT COUNT(*) as c FROM recipes")
    if existing[0]["c"] > 0:
        return

    ph = PLACEHOLDER

    ingredients = [
        "chicken", "eggs", "rice", "garlic", "onion",
        "soy sauce", "ginger", "sesame oil", "cornstarch",
        "beef", "broccoli", "pasta", "tuna", "cheese",
        "tomato", "mixed vegetables", "shrimp", "butter",
        "olive oil", "salt", "pepper", "lemon",
        "tofu", "spinach", "cucumber", "bell pepper", "potato",
        "carrot", "mushroom", "salmon", "bread", "milk", "noodles",
        "pork", "cabbage", "flour", "sugar", "vinegar", "fish sauce",
        "coconut milk", "lime", "cilantro", "chili", "bacon",
        # Filipino pantry extras
        "pork belly", "bay leaf", "annatto", "banana blossom",
        "eggplant", "bitter melon", "kangkong", "sitaw",
        "tamarind", "miso paste", "dried fish", "peanut butter",
        "oxtail", "tripe", "chorizo", "longganisa",
    ]

    insert_ing = f"INSERT INTO ingredients (name) VALUES ({ph}) ON CONFLICT (name) DO NOTHING"
    if not USE_PG:
        insert_ing = f"INSERT OR IGNORE INTO ingredients (name) VALUES ({ph})"
    for ing in ingredients:
        execute(insert_ing, (ing,))

    recipes = [
        # ── Original 14 ──────────────────────────────────────────────────────
        {"name":"Chicken Stir Fry","cook_time":"20 min","difficulty":"Easy","tags":"Asian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Slice chicken into strips and season.\n2. Mix soy sauce, sesame oil, cornstarch.\n3. Stir-fry chicken 3-4 min. Remove.\n4. Stir-fry vegetables 2-3 min.\n5. Return chicken, add sauce, toss, serve.",
         "nutrition":(420,38,32,12),"ingredients":[("chicken","200g"),("mixed vegetables","1.5 cups"),("soy sauce","2 tbsp"),("garlic","3 cloves"),("ginger","1 tsp"),("sesame oil","1 tbsp"),("cornstarch","1 tbsp")]},
        {"name":"Egg Fried Rice","cook_time":"15 min","difficulty":"Easy","tags":"Asian",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Cook rice. Cool.\n2. Scramble eggs in wok. Remove.\n3. Fry garlic, onion.\n4. Add rice, soy sauce, toss.\n5. Return eggs, mix well, serve.",
         "nutrition":(380,22,55,9),"ingredients":[("rice","1 cup"),("eggs","3"),("garlic","2 cloves"),("onion","1 small"),("soy sauce","1 tbsp")]},
        {"name":"Tuna Pasta","cook_time":"18 min","difficulty":"Medium","tags":"Italian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80",
         "instructions":"1. Cook pasta al dente.\n2. Drain tuna, flake.\n3. Sauté garlic in olive oil.\n4. Add tomato, simmer 5 min.\n5. Toss pasta and tuna, serve.",
         "nutrition":(490,34,58,11),"ingredients":[("pasta","100g"),("tuna","150g"),("tomato","2"),("garlic","2 cloves"),("olive oil","1 tbsp")]},
        {"name":"Beef Bowl","cook_time":"25 min","difficulty":"Medium","tags":"High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Slice beef thin.\n2. Marinate in soy sauce, ginger.\n3. Cook rice.\n4. Sear beef 3-4 min.\n5. Serve over rice with garnish.",
         "nutrition":(550,45,42,18),"ingredients":[("beef","200g"),("rice","1 cup"),("soy sauce","2 tbsp"),("ginger","1 tsp"),("onion","1 small")]},
        {"name":"Veggie Omelette","cook_time":"10 min","difficulty":"Easy","tags":"Vegetarian,Low-Cal,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80",
         "instructions":"1. Beat eggs with salt and pepper.\n2. Sauté onion, tomato.\n3. Pour eggs over veggies.\n4. Fold and cook 2 min.\n5. Serve with toast.",
         "nutrition":(310,24,18,14),"ingredients":[("eggs","3"),("tomato","1"),("onion","0.5"),("cheese","30g"),("butter","1 tsp")]},
        {"name":"Garlic Shrimp Pasta","cook_time":"22 min","difficulty":"Medium","tags":"Italian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80",
         "instructions":"1. Cook pasta.\n2. Sauté garlic in butter and olive oil.\n3. Add shrimp, cook 3 min each side.\n4. Toss with pasta and lemon juice.\n5. Season and serve.",
         "nutrition":(520,32,54,16),"ingredients":[("shrimp","200g"),("pasta","100g"),("garlic","4 cloves"),("butter","2 tbsp"),("lemon","0.5"),("olive oil","1 tbsp")]},
        {"name":"Tofu Scramble","cook_time":"12 min","difficulty":"Easy","tags":"Vegetarian,Low-Cal,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
         "instructions":"1. Crumble tofu into a hot pan.\n2. Add garlic and onion, sauté 3 min.\n3. Season with soy sauce and pepper.\n4. Add spinach, cook 2 min until wilted.\n5. Serve with toast.",
         "nutrition":(280,22,18,10),"ingredients":[("tofu","200g"),("garlic","2 cloves"),("onion","0.5"),("soy sauce","1 tbsp"),("spinach","1 cup")]},
        {"name":"Salmon with Garlic Rice","cook_time":"25 min","difficulty":"Medium","tags":"High-Protein,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80",
         "instructions":"1. Season salmon with salt, pepper, lemon.\n2. Pan-sear salmon 4 min each side.\n3. Cook rice with garlic in butter.\n4. Plate rice, top with salmon.\n5. Squeeze lemon, serve.",
         "nutrition":(460,42,38,14),"ingredients":[("salmon","200g"),("rice","1 cup"),("garlic","3 cloves"),("butter","1 tbsp"),("lemon","0.5")]},
        {"name":"Pork Cabbage Stir Fry","cook_time":"18 min","difficulty":"Easy","tags":"Asian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Slice pork thin, marinate in soy sauce and ginger.\n2. Stir-fry pork on high heat 4 min.\n3. Add garlic and onion, cook 1 min.\n4. Add cabbage, toss until wilted.\n5. Season with fish sauce, serve over rice.",
         "nutrition":(390,30,28,13),"ingredients":[("pork","200g"),("cabbage","2 cups"),("garlic","3 cloves"),("ginger","1 tsp"),("soy sauce","2 tbsp"),("fish sauce","1 tbsp")]},
        {"name":"Bacon and Egg Toast","cook_time":"10 min","difficulty":"Easy","tags":"High-Protein",
         "image_url":"https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80",
         "instructions":"1. Fry bacon strips until crispy.\n2. Fry eggs sunny-side up in same pan.\n3. Toast bread until golden.\n4. Layer bacon and egg on toast.\n5. Season with pepper and serve.",
         "nutrition":(420,28,30,20),"ingredients":[("bacon","3 strips"),("eggs","2"),("bread","2 slices"),("butter","1 tsp"),("pepper","to taste")]},
        {"name":"Mushroom and Spinach Pasta","cook_time":"20 min","difficulty":"Easy","tags":"Vegetarian,Italian",
         "image_url":"https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80",
         "instructions":"1. Cook pasta al dente.\n2. Sauté garlic in olive oil.\n3. Add mushrooms, cook until golden.\n4. Add spinach, wilt 1 min.\n5. Toss with pasta, season and serve.",
         "nutrition":(410,18,62,10),"ingredients":[("pasta","100g"),("mushroom","150g"),("spinach","1 cup"),("garlic","3 cloves"),("olive oil","2 tbsp")]},
        {"name":"Coconut Milk Chicken","cook_time":"30 min","difficulty":"Medium","tags":"Asian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Sauté garlic, ginger, chili in oil.\n2. Add chicken pieces, brown 5 min.\n3. Pour in coconut milk, simmer 15 min.\n4. Add fish sauce and lime juice.\n5. Garnish with cilantro, serve with rice.",
         "nutrition":(480,40,22,24),"ingredients":[("chicken","200g"),("coconut milk","200ml"),("garlic","3 cloves"),("ginger","1 tsp"),("chili","1"),("fish sauce","1 tbsp"),("lime","0.5"),("cilantro","to taste")]},
        {"name":"Potato and Egg Hash","cook_time":"22 min","difficulty":"Easy","tags":"Vegetarian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80",
         "instructions":"1. Dice potatoes, boil 8 min until just tender.\n2. Pan-fry potatoes in oil until crispy.\n3. Add onion and bell pepper, cook 3 min.\n4. Crack eggs over hash, cover and cook 3 min.\n5. Season and serve hot.",
         "nutrition":(360,18,48,12),"ingredients":[("potato","2 medium"),("eggs","3"),("onion","1 small"),("bell pepper","0.5"),("olive oil","2 tbsp")]},
        {"name":"Spicy Tuna Rice Bowl","cook_time":"12 min","difficulty":"Easy","tags":"High-Protein,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Cook rice.\n2. Mix tuna with soy sauce, sesame oil, chili.\n3. Slice cucumber thinly.\n4. Assemble: rice base, tuna mix on top.\n5. Add cucumber, drizzle with lime.",
         "nutrition":(380,35,42,8),"ingredients":[("tuna","150g"),("rice","1 cup"),("cucumber","0.5"),("soy sauce","1 tbsp"),("sesame oil","1 tsp"),("chili","0.5"),("lime","0.5")]},

        # ── Filipino Staples (20) ─────────────────────────────────────────────
        {"name":"Chicken Adobo","cook_time":"35 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80",
         "instructions":"1. Combine chicken, soy sauce, vinegar, garlic, bay leaf, pepper.\n2. Marinate 15 min.\n3. Bring to boil, then simmer 20 min.\n4. Fry chicken in oil until golden.\n5. Reduce sauce and pour over. Serve with rice.",
         "nutrition":(480,42,8,28),"ingredients":[("chicken","500g"),("soy sauce","4 tbsp"),("vinegar","3 tbsp"),("garlic","6 cloves"),("bay leaf","3"),("pepper","1 tsp")]},
        {"name":"Pork Adobo","cook_time":"40 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80",
         "instructions":"1. Combine pork belly, soy sauce, vinegar, garlic, bay leaf.\n2. Marinate 20 min.\n3. Simmer covered 25 min until tender.\n4. Uncover and reduce sauce 5 min.\n5. Serve over rice.",
         "nutrition":(560,36,6,38),"ingredients":[("pork belly","400g"),("soy sauce","4 tbsp"),("vinegar","3 tbsp"),("garlic","5 cloves"),("bay leaf","2"),("sugar","1 tsp")]},
        {"name":"Sinangag (Garlic Fried Rice)","cook_time":"10 min","difficulty":"Easy","tags":"Filipino,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Heat oil in pan.\n2. Fry garlic until golden and crispy.\n3. Add day-old rice, toss well.\n4. Season with salt and fish sauce.\n5. Top with crispy garlic bits, serve hot.",
         "nutrition":(320,6,62,6),"ingredients":[("rice","2 cups cooked"),("garlic","6 cloves"),("olive oil","2 tbsp"),("fish sauce","1 tbsp"),("salt","to taste")]},
        {"name":"Tapsilog","cook_time":"20 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Slice beef thin, marinate in soy sauce, garlic, sugar overnight.\n2. Pan-fry marinated beef 3 min each side.\n3. Fry eggs sunny-side up.\n4. Serve beef and egg over sinangag.\n5. Add vinegar dipping sauce on side.",
         "nutrition":(620,46,52,22),"ingredients":[("beef","200g"),("eggs","2"),("rice","1 cup"),("soy sauce","3 tbsp"),("garlic","4 cloves"),("sugar","1 tbsp"),("vinegar","2 tbsp")]},
        {"name":"Chicken Tinola","cook_time":"40 min","difficulty":"Easy","tags":"Filipino,High-Protein,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Sauté ginger and onion in oil.\n2. Add chicken pieces, brown 5 min.\n3. Pour water, bring to boil.\n4. Simmer 20 min. Add chili leaves.\n5. Season with fish sauce, serve hot.",
         "nutrition":(320,38,12,10),"ingredients":[("chicken","400g"),("ginger","2 tbsp"),("onion","1"),("garlic","3 cloves"),("fish sauce","2 tbsp"),("chili","2 leaves")]},
        {"name":"Sinigang na Baboy","cook_time":"45 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Boil pork ribs 5 min, discard water.\n2. Add fresh water, bring to boil.\n3. Add onion, tomato, simmer 25 min.\n4. Add tamarind, sitaw, eggplant, kangkong.\n5. Season with fish sauce, simmer 5 min.",
         "nutrition":(420,32,18,22),"ingredients":[("pork","400g"),("tamarind","1 packet"),("eggplant","1"),("sitaw","1 cup"),("kangkong","2 cups"),("tomato","2"),("onion","1"),("fish sauce","2 tbsp")]},
        {"name":"Ginisang Monggo","cook_time":"40 min","difficulty":"Easy","tags":"Filipino,Vegetarian,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Sauté garlic, onion, tomato in oil.\n2. Add mung beans, pour water.\n3. Simmer 25 min until soft.\n4. Add spinach, season with fish sauce.\n5. Optional: add fried dried fish on top.",
         "nutrition":(310,20,46,6),"ingredients":[("mung beans","1 cup"),("garlic","3 cloves"),("onion","1"),("tomato","2"),("spinach","2 cups"),("fish sauce","2 tbsp")]},
        {"name":"Tortang Talong","cook_time":"20 min","difficulty":"Easy","tags":"Filipino,Vegetarian,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
         "instructions":"1. Roast eggplant over flame until charred.\n2. Peel skin, flatten with fork.\n3. Beat eggs with salt and pepper.\n4. Dip eggplant in egg mixture.\n5. Pan-fry until golden. Serve with rice and tomato.",
         "nutrition":(280,14,22,14),"ingredients":[("eggplant","2 large"),("eggs","3"),("garlic","2 cloves"),("tomato","1"),("salt","to taste"),("pepper","to taste")]},
        {"name":"Champorado","cook_time":"25 min","difficulty":"Easy","tags":"Filipino,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Cook rice in water until thick porridge.\n2. Add cocoa powder and sugar, stir.\n3. Simmer 10 min, stir constantly.\n4. Add milk for creaminess.\n5. Serve with dried fish (tuyo) on the side.",
         "nutrition":(360,8,72,6),"ingredients":[("rice","1 cup"),("cocoa powder","3 tbsp"),("sugar","2 tbsp"),("milk","0.5 cup"),("salt","pinch")]},
        {"name":"Arroz Caldo","cook_time":"35 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Sauté ginger, garlic, onion until fragrant.\n2. Add chicken, cook 5 min.\n3. Add rice and water, simmer 20 min.\n4. Season with fish sauce.\n5. Top with toasted garlic, green onion, boiled egg.",
         "nutrition":(420,32,48,10),"ingredients":[("chicken","300g"),("rice","0.5 cup"),("ginger","2 tbsp"),("garlic","4 cloves"),("onion","1"),("eggs","2"),("fish sauce","2 tbsp")]},
        {"name":"Bistek Tagalog","cook_time":"25 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Marinate beef in soy sauce, lemon, sugar 30 min.\n2. Pan-fry beef 2 min each side. Set aside.\n3. Sauté onion rings in same pan until soft.\n4. Return beef, pour remaining marinade.\n5. Simmer 3 min, serve over rice.",
         "nutrition":(490,40,12,28),"ingredients":[("beef","250g"),("soy sauce","4 tbsp"),("lemon","2"),("onion","2 large"),("sugar","1 tsp"),("garlic","3 cloves")]},
        {"name":"Pork Nilaga","cook_time":"50 min","difficulty":"Easy","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Boil pork in water with onion and peppercorns.\n2. Skim scum, simmer 30 min until tender.\n3. Add potato and carrot, cook 10 min.\n4. Add cabbage, cook 3 min.\n5. Season with salt and fish sauce.",
         "nutrition":(440,34,24,22),"ingredients":[("pork","400g"),("potato","2 medium"),("carrot","1"),("cabbage","2 cups"),("onion","1"),("fish sauce","2 tbsp"),("pepper","1 tsp")]},
        {"name":"Menudo","cook_time":"40 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Sauté garlic, onion, tomato.\n2. Add pork cubes, cook 5 min.\n3. Add potato, carrot, bell pepper.\n4. Pour soy sauce and tomato sauce.\n5. Simmer 20 min until thick. Serve with rice.",
         "nutrition":(520,36,38,20),"ingredients":[("pork","300g"),("potato","2 medium"),("carrot","1"),("tomato","2"),("bell pepper","1"),("soy sauce","3 tbsp"),("garlic","4 cloves"),("onion","1")]},
        {"name":"Afritada","cook_time":"40 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Brown chicken pieces in hot oil.\n2. Sauté garlic, onion in same pan.\n3. Add tomato, patis, chicken stock.\n4. Add potato, carrot, bell pepper.\n5. Simmer 20 min until potatoes are done.",
         "nutrition":(460,40,32,16),"ingredients":[("chicken","400g"),("potato","2 medium"),("carrot","1"),("tomato","3"),("bell pepper","1"),("garlic","4 cloves"),("onion","1"),("fish sauce","2 tbsp")]},
        {"name":"Pancit Bihon","cook_time":"25 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Soak bihon noodles 10 min.\n2. Sauté garlic, onion, chicken in oil.\n3. Add carrot, cabbage, cook 3 min.\n4. Add noodles, soy sauce, chicken stock.\n5. Toss until noodles absorb liquid. Top with calamansi.",
         "nutrition":(420,24,58,10),"ingredients":[("noodles","200g"),("chicken","150g"),("carrot","1"),("cabbage","1 cup"),("garlic","3 cloves"),("onion","1"),("soy sauce","3 tbsp")]},
        {"name":"Lomi","cook_time":"25 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Boil pork or chicken in broth.\n2. Add thick egg noodles, cook 5 min.\n3. Add vegetables: cabbage, carrot.\n4. Drizzle cornstarch slurry to thicken.\n5. Crack eggs in, stir, serve immediately.",
         "nutrition":(490,28,62,14),"ingredients":[("noodles","250g"),("pork","150g"),("eggs","2"),("cabbage","1 cup"),("carrot","1"),("garlic","3 cloves"),("soy sauce","2 tbsp"),("cornstarch","2 tbsp")]},
        {"name":"Bicol Express","cook_time":"35 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Blanch chili in boiling water 2 min. Drain.\n2. Sauté garlic, onion, shrimp paste.\n3. Add pork belly, cook until fat renders.\n4. Pour coconut milk, simmer 15 min.\n5. Add chili, season with fish sauce. Simmer 5 min.",
         "nutrition":(580,28,12,44),"ingredients":[("pork belly","300g"),("chili","8 pieces"),("coconut milk","400ml"),("garlic","4 cloves"),("onion","1"),("shrimp paste","1 tbsp"),("fish sauce","1 tbsp")]},
        {"name":"Kare-Kare","cook_time":"60 min","difficulty":"Hard","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Boil oxtail or tripe until tender, 45 min.\n2. Sauté onion, garlic in annatto oil.\n3. Add meat and broth.\n4. Stir in peanut butter and rice flour.\n5. Add eggplant, sitaw, banana blossom. Simmer 10 min. Serve with bagoong.",
         "nutrition":(620,42,28,38),"ingredients":[("oxtail","500g"),("peanut butter","4 tbsp"),("eggplant","1"),("sitaw","1 cup"),("banana blossom","1 cup"),("onion","1"),("garlic","4 cloves"),("annatto","1 tbsp")]},
        {"name":"Sisig","cook_time":"30 min","difficulty":"Medium","tags":"Filipino,High-Protein",
         "image_url":"https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
         "instructions":"1. Grill or boil pork belly and face until tender.\n2. Chop finely into small pieces.\n3. Fry chopped pork on sizzling plate.\n4. Add onion, chili, soy sauce, calamansi.\n5. Top with egg, mix at table. Serve sizzling.",
         "nutrition":(540,32,8,40),"ingredients":[("pork belly","300g"),("onion","1 large"),("chili","3"),("soy sauce","2 tbsp"),("lemon","1"),("eggs","2"),("garlic","3 cloves")]},
        {"name":"Lugaw (Rice Porridge)","cook_time":"30 min","difficulty":"Easy","tags":"Filipino,Low-Cal",
         "image_url":"https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
         "instructions":"1. Sauté ginger in oil until fragrant.\n2. Add rice and water, ratio 1:8.\n3. Bring to boil, reduce and simmer 20 min.\n4. Stir often until porridge consistency.\n5. Top with green onion, garlic, boiled egg.",
         "nutrition":(260,8,50,4),"ingredients":[("rice","0.5 cup"),("ginger","2 tbsp"),("garlic","3 cloves"),("eggs","2"),("fish sauce","1 tbsp"),("onion","1")]},
    ]
